version: '3.3'

services:
  backend:
    image: taan-chat-system_backend:lastest
    build: ./Backend
    container_name: backend
    depends_on:
      - database
    ports:
      - 3001:3001

  frontend:
    image: taan-chat-system_backend
    build: ./Frontend
    image: taan-chat-system_frontend:lastest
    container_name: frontend
    ports:
      - 5000:5000
  
  database:
    build: ./Database
    image: taan-chat-system_database:lastest
    container_name: database
    ports:
      - 3306:3306
      
  proxy:
    build: ./ProxyServer
    container_name: proxy
    depends_on:
      - backend
    volumes:
      - ./ProxyServer:/etc/nginx
    links:
      - backend
    ports:
      - 8080:8080
  
  redis:
    image: redis
  
