version: '3.3'

services:
  database:
    image: taan02991/database
    container_name: database
    ports:
      - 3306:3306

  backend:
    image: taan02991/backend
    container_name: backend
    depends_on:
      - database
  
  backend-secondary:
    image: taan02991/backend
    container_name: backend-secondary
    depends_on:
      - backend

  frontend:
    image: taan02991/frontend
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SOCKET_GATEWAY=localhost:8080
  
  proxy:
    image: taan02991/proxy
    container_name: proxy
    depends_on:
      - backend
      - backend-secondary
    ports:
      - 8080:8080

  redis:
    image: redis