version: '3.3'

services:
  backend:
    build: ./Backend
    container_name: backend
    depends_on:
      - database

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - 5000:5000
  
  database:
    build: ./Database
    container_name: database
    ports:
      - 3306:3306
