version: '3.3'

services:
  backend:
    build: ./Backend
    container_name: backend
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database
  
  backend-secondary:
    image: taan-chat-system_backend
    container_name: backend-secondary
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend

  frontend:
    build: ./Frontend
    container_name: frontend
    volumes:
      - ./Frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
  
  proxy:
    build: ./ProxyServer
    container_name: proxy
    depends_on:
      - backend
      - backend-secondary
    volumes:
      - ./ProxyServer:/etc/nginx
    links:
      - backend
    ports:
      - 8080:8080
  
  database:
    build: ./Database
    container_name: database
    ports:
      - 3306:3306